#
# Copyright (C) GridGain Systems. All Rights Reserved.
#  _________        _____ __________________        _____
#  __  ____/___________(_)______  /__  ____/______ ____(_)_______
#  _  / __  __  ___/__  / _  __  / _  / __  _  __ `/__  / __  __ \
#  / /_/ /  _  /    _  /  / /_/ /  / /_/ /  / /_/ / _  /  _  / / /
#  \____/   /_/     /_/   \_,__/   \____/   \__,_/  /_/   /_/ /_/
#

{{- if .Values.clusterConfig.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "gridgain9.fullname" .) "cluster-config" }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "gridgain9.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- with .Values.clusterConfig.createSecret }}
  cluster.json: {{ .content | b64enc }}
{{- end }}
{{- end }}
