apiVersion: v1
appVersion: "2025.4"
description: Helm chart to deploy Control Center Spring applications
name: cc-spring-app
keywords:
- gridgain
- cloud-connector
- cc-spring-app
home: https://www.gridgain.com/products/control-center
version: 1.0.5
