apiVersion: v2
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: 8.9.11

description: GridGain is a Unified Real-Time Data Platform by the original creators of Apache Ignite. It enables a simplified and optimized data architecture for enterprises that require extreme speed, massive scale, and high availability from their data ecosystem.
home: https://www.gridgain.com/

maintainers:
- name: GridGain Systems, Inc. All Rights Reserved
  url: https://www.gridgain.com/

name: gridgain
sources:
- https://github.com/gridgain/helm-charts/tree/main/charts/gridgain

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.5
